# Travis-CI.org build script

# container-based infrastructure
sudo: false

# install:
#   - sudo apt-get update -qq
#   - sudo apt-get install -y libnetpbm10 libnetpbm10-dev wcslib-dev libcfitsio3 libcfitsio3-dev python-numpy swig gsl-bin libgsl0-dev python-sphinx sphinx-common python-matplotlib python-scipy python-mock 
#   - sudo pip install numpydoc
# # python-numpydoc -- not available until Ubuntu 14.04 trusty

install:
    - pip install --user numpy==1.11.0
    - pip install --user matplotlib==1.5.1
    - pip install numpydoc -t $HOME/numpydoc
    - pip install --user coveralls
    - pip install --user astropy
    - pip install --user fitsio
    - pip install --user photutils
    # - easy_install3 --user pip
    # - pip3 install --user numpy==1.11.0
    # - pip3 install --user matplotlib==1.5.1
    # - pip3 install numpydoc -t $HOME/numpydoc
    # - pip3 install --user coveralls
    # - pip3 install --user astropy
    # - pip3 install --user fitsio
    # - pip3 install --user photutils

# This failed due to error building scipy (blas)
# language: python
# python:
#   - "2.7"
#   - "2.7_with_system_site_packages"
#   - "3.4"
# install:
#     - pip install numpy
#     - python -c "from __future__ import print_function; import numpy; print(numpy.__file__)"
#     - python -c "from __future__ import print_function; import numpy.distutils.system_info as sysinfo; print([(x, sysinfo.get_info(x)) for x in ['atlas', 'lapack', 'blas', 'lapack_src', 'blas_src']])"
#     - python -c "from __future__ import print_function; import numpy; print(numpy.__config__.show())"
#     - pip install scipy
#     - pip install matplotlib
#     - pip install numpydoc -t $HOME/numpydoc
#     - pip install coveralls
#     - pip install astropy
#     - pip install fitsio
#     - pip install photutils

language: c
compiler:
    - gcc


before_script:
    - export WCSLIB_INC="-I/usr/include/wcslib-4.8.3"
    - export WCSLIB_LIB="-lwcs"
    - if [ ! -d "$HOME/astrometry.net" ]; then (cd $HOME; git clone https://github.com/dstndstn/astrometry.net.git); fi
    - (cd $HOME/astrometry.net && git pull) || (rm -Rf $HOME/astrometry.net && cd $HOME && git clone https://github.com/dstndstn/astrometry.net.git);
    - (cd $HOME/astrometry.net && make && make py)
    - if [ ! -d "$HOME/tractor-git" ]; then (cd $HOME; git clone https://github.com/dstndstn/tractor.git tractor-git); fi
    - (cd $HOME/tractor-git && git pull) || (rm -Rf $HOME/tractor-git && cd $HOME && git clone https://github.com/dstndstn/tractor.git tractor-git);
    - (cd $HOME/tractor-git && make)
    # pip install fitsio instead
    #- if [ ! -d "$HOME/fitsio-git" ]; then (cd $HOME; git clone https://github.com/esheldon/fitsio.git fitsio-git); fi
    #- (cd $HOME/fitsio-git && git pull) || (rm -Rf $HOME/fitsio-git && cd $HOME && git clone https://github.com/esheldon/fitsio.git fitsio-git);
    #- (rm -Rf $HOME/fitsio-git && cd $HOME && git clone https://github.com/esheldon/fitsio.git fitsio-git);
    #- (cd $HOME/fitsio-git && python setup.py install --home $HOME/fitsio)
    #- ln -s $HOME/fitsio/lib/python/fitsio .
    - ln -s $HOME/astrometry.net astrometry
    - ln -s $HOME/tractor-git/tractor .
    - ln -s $HOME/tractor-git/wise .
    - mkdir -p $HOME/dust/maps
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_ngp.fits)
    - (cd $HOME/dust/maps && wget -c http://portal.nersc.gov/project/cosmo/temp/dstn/travis-ci/maps/SFD_dust_4096_sgp.fits)
    - export DUST_DIR=$HOME/dust

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)/py:$(pwd):$HOME/numpydoc
    - (cd doc && make)
    - echo $PYTHONPATH
    - python -c "import numpy; print numpy.__file__"
    - python -c "import matplotlib; print matplotlib.__file__"
    - python -c "import fitsio; print fitsio.__file__"
    - (cd py && coverage run test/runbrick_test.py travis)
    - python3 -c "import numpy; print(numpy.__file__)"
    - python3 -c "import matplotlib; print(matplotlib.__file__)"
    - python3 -c "import fitsio; print(fitsio.__file__)"
# Ugh, travis's "precise" distro includes numpy 1.6.1
# (np.fft.rfftfreq doesn't exist)
# For python3 it's also numpy 1.6

after_success:
    - (cd py && coveralls debug)
    - (cd py && coveralls)

addons:
  apt:
    packages:
    - libnetpbm10
    - libnetpbm10-dev
    - wcslib-dev
    - libcfitsio3
    - libcfitsio3-dev
    - swig
    - gsl-bin
    - python-sphinx
    - python-mock
    #- python-numpy   # try just to get blas deps
    #- python-matplotlib
    - python-scipy
    - python3
    - python3-setuptools
    #- python3-numpy


# python-numpydoc is only available in 'trusty' and later.
#    - python-numpydoc

# not whitelisted... needed?
#    - libgsl10-dev

cache:
  directories:
  - $HOME/astrometry.net
  - $HOME/tractor-git
  #- $HOME/fitsio-git
  - $HOME/.local
  - $HOME/dust
